default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: odds_odds_development

test:
  <<: *default
  database: odds_odds_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cable:
  <<: *default
  database: odds_odds_cable_production
  url: <%= ENV['CABLE_DATABASE_URL'] %>

queue:
  <<: *default
  database: odds_odds_queue_production
  url: <%= ENV['QUEUE_DATABASE_URL'] %>