default: &default
  adapter: postgresql
  encoding: unicode
  database: odds_ecom_db_ss40
  pool: 20
  username: odds_ecom_db_ss40_user
  password: 3YvXSq7uxe6kTvAh3ixbpCgK5gML6dYX
  host: dpg-d0lknmruibrs73adnvvg-a.singapore-postgres.render.com
  timeout: 5000

development:
  primary:
    adapter: postgresql
    encoding: unicode
    database: odds_ecom_db_ss40
    pool: 20
    username: odds_ecom_db_ss40_user
    password: 3YvXSq7uxe6kTvAh3ixbpCgK5gML6dYX
    host: dpg-d0lknmruibrs73adnvvg-a.singapore-postgres.render.com
    port: 5432
    sslmode: require
    default_role: writer

  reading:
    adapter: postgresql
    encoding: unicode
    database: odds_ecom_db_ss40
    pool: 20
    username: odds_ecom_db_ss40_user
    password: 3YvXSq7uxe6kTvAh3ixbpCgK5gML6dYX
    host: dpg-d0lknmruibrs73adnvvg-a.singapore-postgres.render.com
    port: 5432
    replica: true

  queue:
    adapter: postgresql
    encoding: unicode
    pool: 20
    database: odds_ecom_db_ss40
    username: odds_ecom_db_ss40_user
    password: 3YvXSq7uxe6kTvAh3ixbpCgK5gML6dYX
    host: dpg-d0lknmruibrs73adnvvg-a.singapore-postgres.render.com
    port: 5432

test:
  primary:
    adapter: postgresql
    encoding: unicode
    database: odds_ecom_db_ss40
    pool: 20
    username: odds_ecom_db_ss40_user
    password: 3YvXSq7uxe6kTvAh3ixbpCgK5gML6dYX
    host: dpg-d0lknmruibrs73adnvvg-a.singapore-postgres.render.com
    port: 5432
    default_role: writer

  queue:
    adapter: postgresql
    encoding: unicode
    pool: 20
    database: odds_ecom_db_ss40
    username: odds_ecom_db_ss40_user
    password: 3YvXSq7uxe6kTvAh3ixbpCgK5gML6dYX
    host: dpg-d0lknmruibrs73adnvvg-a.singapore-postgres.render.com
    port: 5432

production:
  primary:
    adapter: postgresql
    encoding: unicode
    database: odds_ecom_db_ss40
    pool: 20
    username: odds_ecom_db_ss40_user
    password: 3YvXSq7uxe6kTvAh3ixbpCgK5gML6dYX
    host: dpg-d0lknmruibrs73adnvvg-a.singapore-postgres.render.com
    port: 5432
    sslmode: require
    default_role: writer

  queue:
    adapter: postgresql
    encoding: unicode
    pool: 20
    database: odds_ecom_db_ss40
    username: odds_ecom_db_ss40_user
    password: 3YvXSq7uxe6kTvAh3ixbpCgK5gML6dYX
    host: dpg-d0lknmruibrs73adnvvg-a.singapore-postgres.render.com
    port: 5432

  cache:
    adapter: postgresql
    encoding: unicode
    database: odds_ecom_db_ss40
    username: odds_ecom_db_ss40_user
    password: 3YvXSq7uxe6kTvAh3ixbpCgK5gML6dYX
    host: dpg-d0lknmruibrs73adnvvg-a.singapore-postgres.render.com
    port: 5432

cable:
  <<: *default
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
