default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: odds_odds_db
  pool: 5
  username: odds_odds_db_user
  password: V8H3X58qVum4X7QIYU25P5VTEEtj722K
  host: dpg-cvom0dre5dus73c66mh0-a.oregon-postgres.render.com
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: odds_odds_db
  pool: 5
  username: odds_odds_db_user
  password: V8H3X58qVum4X7QIYU25P5VTEEtj722K
  host: dpg-cvom0dre5dus73c66mh0-a.oregon-postgres.render.com
  port: 5432

production:
  primary:
    adapter: postgresql
    encoding: unicode
    database: odds_odds_db
    pool: 5
    username: odds_odds_db_user
    password: V8H3X58qVum4X7QIYU25P5VTEEtj722K
    host: dpg-cvom0dre5dus73c66mh0-a.oregon-postgres.render.com
    port: 5432

  queue:
    adapter: postgresql
    encoding: unicode
    database: odds_odds_db
    username: odds_odds_db_user
    password: V8H3X58qVum4X7QIYU25P5VTEEtj722K
    host: dpg-cvom0dre5dus73c66mh0-a.oregon-postgres.render.com
    port: 5432

  cache:
    adapter: postgresql
    encoding: unicode
    database: odds_odds_db
    username: odds_odds_db_user
    password: V8H3X58qVum4X7QIYU25P5VTEEtj722K
    host: dpg-cvom0dre5dus73c66mh0-a.oregon-postgres.render.com
    port: 5432

cable:
  <<: *default
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>