default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: your_development_database_name

test:
  <<: *default
  database: your_test_database_name

production:
  <<: *default
  database: odds_odds_db
  username: odds_odds_db_user
  password: <%= ENV['DATABASE_PASSWORD'] %> # แนะนำให้ใช้ environment variable
  host: dpg-cvom0dre5dus73c66mh0-a.oregon-postgres.render.com
  port: 5432 # เพิ่ม port เข้าไป

  queue:
    <<: *default
    database: odds_odds_db
    username: odds_odds_db_user
    password: <%= ENV['DATABASE_PASSWORD'] %> # แนะนำให้ใช้ environment variable
    host: dpg-cvom0dre5dus73c66mh0-a.oregon-postgres.render.com
    port: 5432 # เพิ่ม port เข้าไป

cable:
  <<: *default
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>